#!/bin/bash

timelapseName=timelapse-`date +\%Y-\%m-\%d-\%H-\%M-%S`
mkdir -p /home/pi/captures/$timelapseName
jpegfilename=/home/pi/captures/$timelapseName/must-rotate-180-$timelapseName-%07d.jpg
/usr/bin/raspistill -o $jpegfilename -t 108000000 -tl 2400
# /usr/bin/raspistill -o $jpegfilename -t 108000000 -tl 2400 -ex night
